# Generated by Django 5.2.13 on 2026-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
    ]
